# Generated by Django 5.0.7 on 2024-08-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("rating", models.IntegerField()),
                ("fav_character", models.CharField(max_length=20)),
            ],
        ),
    ]
